version: '3.6'
services:

  wordpress:
    image: wordpress-apachessl
    ports:
      - '443:443'
    build: ./wordpress-build/apachessl
    container_name: ${APP_NAME}-wordpress
    restart: always
    volumes: 
      - ./wordpress:/var/www/html
      - ./config/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./certs/cert.pem:/etc/ssl/certs/ssl-cert-snakeoil.pem:ro
      - ./certs/key.pem:/etc/ssl/private/ssl-cert-snakeoil.key:ro
